Switch TestVisitor to Lang_C via -x c
...instead of -std=c99, as the latter lead to

  error: invalid argument '-std=c99' not allowed with 'C++'

complaints in test logs

Differential Revision: https://reviews.llvm.org/D34417


git-svn-id: https://llvm.org/svn/llvm-project/cfe/trunk@306373 91177308-0d34-0410-b5e6-96231b3b80d8