Removed unused variable [NFC]
The compiler warned:
../tools/clang/lib/Sema/SemaType.cpp:6788:31: error: unused variable 'AT' [-Werror,-Wunused-variable]
    if (const AttributedType *AT = S.getCallingConvAttributedType(type)) {
                              ^
1 error generated.

git-svn-id: https://llvm.org/svn/llvm-project/cfe/trunk@340251 91177308-0d34-0410-b5e6-96231b3b80d8